version: '3.9'

services:

  backend:
    build: .
    container_name: backend
    command: python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn core.wsgi --bind 0.0.0.0:8080
    volumes:
      - .:/usr/src/app/
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    expose:
      - "8080" 
    environment:
      - DEBUG=False
    # env_file:
    #   - ./.env.staging
    depends_on:
      - redis

  redis:
    container_name: redis
    image: docker.arvancloud.ir/redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning 

  worker:
    build: .
    container_name: celery_worker
    command: celery -A core worker --loglevel=info
    depends_on:
      - redis
      - backend
    volumes:
      - .:/usr/src/app/
    # env_file:
    #   - ./.env.staging

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A core beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - redis
      - backend
    volumes:
      - .:/usr/src/app/
    # env_file:
    #   - ./.env.staging

  nginx:
    image: docker.arvancloud.ir/nginx:latest
    container_name: nginx
    ports:
      - "80:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    depends_on:
      - backend



volumes:
  static_volume:
  media_volume: