# Generated by Django 4.2.2 on 2025-01-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_articles_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='artilces', to='blog.category'),
        ),
    ]
