# Generated by Django 4.2 on 2023-12-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_articles_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='categories',
        ),
        migrations.AddField(
            model_name='articles',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='artilces', to='blog.category'),
        ),
    ]
